name: GuideChimp - Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Setup Node.js environment
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Checkout GuideChimp
      uses: actions/checkout@v2
      with:
        path: guidechimp-core

    - name: Read GuideChimp Plugins version
      id: guidechimp_plugins_version
      uses: notiz-dev/github-action-json-property@release
      with:
        path: './guidechimp-core/package.json'
        prop_path: 'plugins.guidechimp-plugins'

    - name: Checkout GuideChimp Plugins (v${{steps.guidechimp_plugins_version.outputs.prop}})
      uses: actions/checkout@v2
      with:
        path: guidechimp-plugins
        repository: Labs64/GuideChimp-plugins
        ref: ${{steps.guidechimp_plugins_version.outputs.prop}}
        token: ${{ secrets.GUIDECHIMP_PAT }}

    - name: npm install, build, and test
      run: |
        ls -la .
        ls -la guidechimp-core/
        ls -la guidechimp-plugins/
        cd guidechimp-core
        npm ci
        npm run build --if-present
        npm test
        ls -la -R dist/
        cd ../guidechimp-plugins
        npm ci
        npm run build --if-present
        ls -la -R dist/
        rsync -av dist/ ../guidechimp-core/dist
        ls -la -R ../guidechimp-core/dist/plugins
        cat ../guidechimp-core/dist/plugins/lazyLoading.js
        cat ../guidechimp-core/dist/plugins/triggers.js
        cat ../guidechimp-core/dist/plugins/iFrames.js
