name: GuideChimp - Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout GuideChimp
      uses: actions/checkout@v2
      with:
        path: guidechimp-core

    - name: Read GuideChimp Plugins version
      id: guidechimp_plugins_version
      uses: notiz-dev/github-action-json-property@release
      with:
        path: './guidechimp-core/package.json'
        prop_path: 'plugins.guidechimp-plugins'

    - name: Print guidechimp_plugins_version
      run: echo ${{steps.guidechimp_plugins_version.outputs.prop}}

    - name: Checkout GuideChimp Plugins
      uses: actions/checkout@v2
      with:
        path: guidechimp-plugins
        repository: Labs64/GuideChimp-plugins
        ref: '0.0.1'
        token: ${{ secrets.GUIDECHIMP_PAT }}

    - name: Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: npm install, build, and test
      run: |
        ls -la .
        ls -la guidechimp-core/
        ls -la guidechimp-plugins/
        cd guidechimp-core
        npm ci
        npm run build --if-present
        npm test
        ls -la -R dist/
